// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhxXRBITDgMgeDFwz264BWyK2BowaruFo',
    appId: '1:700589840093:web:d53a074857484a02816d34',
    messagingSenderId: '700589840093',
    projectId: 'gamestation-31a73',
    authDomain: 'gamestation-31a73.firebaseapp.com',
    storageBucket: 'gamestation-31a73.appspot.com',
    measurementId: 'G-690SRFFTJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATssVE9ge6kngjrSEpgHcoHJPgzyv6ung',
    appId: '1:700589840093:android:cc41e66781ff6e1c816d34',
    messagingSenderId: '700589840093',
    projectId: 'gamestation-31a73',
    storageBucket: 'gamestation-31a73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0WYkqq-qeJYbfDgIcVtrbxk5FITTePvY',
    appId: '1:700589840093:ios:76696d0ebcc59708816d34',
    messagingSenderId: '700589840093',
    projectId: 'gamestation-31a73',
    storageBucket: 'gamestation-31a73.appspot.com',
    androidClientId: '700589840093-skhv1gvrui3gu7afn547dhgdtecubtji.apps.googleusercontent.com',
    iosClientId: '700589840093-b3b3ucms64llmipll083k50abmcrsp1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamestation',
  );
}
